### ISSUE TITLE
support old XMR

### ISSUE THREAD

**Issue by thomarite** [ipcjk/brocadecli#1]
Hi 

First of all, apologies if I doing/saying anything wrong as I am quite newbie dealing with issues in Go, github, etc

I like your project and would like to use it in my employer Brocade MLX/XMR state. At the moment I can't make it work with old XMR from our lab as it is using old ciphers :( and can't really upgrade it

~/automation/mlxsh/release$ ./mlxsh -hostname xxx -script "show ip bgp summary"
╔══════════════════════════════════════════════════════════════════════╗
║xxx                                                       ║
║No success:                                                           ║
║ssh: handshake failed: ssh: no common algorithm for client to server cipher; client offered: [aes128-ctr aes192-ctr aes256-ctr aes128-gcm@openssh.com arcfour256 arcfour128], server offered: [aes256-cbc aes192-cbc aes128-cbc 3des-cbc]║
╚══════════════════════════════════════════════════════════════════════╝

I am trying to add this workaround in place in your code

https://github.com/golang/go/issues/20201

Are you ok if I can try to add that?

Thanks!

**Comment by ipcjk** [comment]
New built is here:
https://github.com/ipcjk/mlxsh/releases/tag/0.2a
 
Thank you very much for your input. I have added "aes128-cbc" and "3des-cbc" and tested things with the Turboiron 24x here. "aes256-cbc", "aes192-cbc" is not supported in ssh-go. 

```bash
./mlxsh -label "type=turboiron"  -script 'show version' | grep uptime
The system uptime is 556 days 12 hours 52 minutes 59 seconds 
```

Looks good for me.

**Comment by thomarite** [comment]
Thanks Jorg! I am going to test and let you know

Regards
tomas

**Comment by thomarite** [comment]
Hi Jorg

I have tried and it seems the SSH connection is established but it is
failing somehow as my box is not responding:

 ./mlxsh -hostname co1pr01.yb.lmax -script "show ip bgp summary" -debug
╔══════════════════════════════════════════════════════════════════════╗
║co1pr01.yb.lmax                                                       ║
║No success:                                                           ║
║EOF                                                                   ║
Timed out waiting for incoming buffer
╚══════════════════════════════════════════════════════════════════════╝


And this the YAML config:


- Hostname: co1pr01.yb.lmax
  Username: test1
  Password: xxxx
  SSHPort: 22
  #EnablePassword: xxxx
  SpeedMode: False
  Labels:
    location: yb
    environment: lab
    type: xmr

I have tried with and without enable password

This is the SSH config in my XMR

SSH@co1pr01#show ip ssh config
SSH server                 : Enabled
SSH port                   : tcp\22
Host Key                   : DSA 1024
Encryption                 : AES-256, AES-192, AES-128, 3-DES
Permit empty password      : No
Authentication methods     : Password, Public-key, Interactive
Authentication retries     : 3
Login timeout (seconds)    : 120
Idle timeout (minutes)     : 0
Strict management VRF      : Disabled
SCP                        : Enabled
SSH IPv4 clients           : All
SSH IPv6 clients           : All
SSH IPv4 access-group      : SSH_ACCESS
SSH IPv6 access-group      :
SSH Client Keys            :
SSH@co1pr01#

The ACL allows access form my source IP.

Any idea what I am doing wrong?

**Comment by ipcjk** [comment]
I feel very sorry that things don't work.

When you do a login via SSH, do you land directly in privileged mode? Is 
"aaa authentication login privilege-mode" configured?

**Comment by thomarite** [comment]
Yes, we have "aaa authentication login privilege-mode" .

As well, we have a banner, I have removed it and same issue :(

**Comment by ipcjk** [comment]
Great, please check if
https://github.com/ipcjk/mlxsh/releases/download/0.2b/release.tar.gz
resolves your issue.

**Comment by thomarite** [comment]
It works! Thanks! I have used it on MLXe and XMR. All good!

**Comment by thomarite** [comment]
marking the issue as solved. thanks!
